openapi: 3.0.3
info:
  title: STD23020 - TD3
  version: '1.0.3'
servers:
  - url: https://localhost.std23020.com
paths:
  /meals:
    get:
      summary: List all meals
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: Page number for pagination
        - in: query
          name: pageSize
          schema:
            type: integer
          required: false
          description: Number of items per page
      responses:
        200:
          description: List of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      summary: Create a new meal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMeal'
        required: true
      responses:
        201:
          description: Meal created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
    put:
      summary: Update an existing meal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMeal'
        required: true
      responses:
        200:
          description: Meal updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
    delete:
      summary: Delete a meal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MealIdentifier'
        required: true
      responses:
        204:
          description: Meal deleted successfully

components:
  schemas:
    Meal:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the meal
        name:
          type: string
          description: Name of the meal
        price:
          type: number
          format: decimal
          description: Price of the meal
      required:
        - id
        - name
        - price
    CreateMeal:
      type: object
      properties:
        name:
          type: string
          description: Name of the meal
        price:
          type: number
          format: decimal
          description: Price of the meal
      required:
        - name
        - price
    UpdateMeal:
      type: object
      properties:
        name:
          type: string
          description: Name of the meal
        price:
          type: number
          format: decimal
          description: Price of the meal
      required:
        - name
        - price
    MealIdentifier:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the meal
      required:
        - id
